name: mkdocs-docker-image-live-dev
services:
  docs:
    build:
      context: ../..
      dockerfile: docs/docker/dockerfile
    container_name: mkdocs
    hostname: mkdocs
    volumes:
      - ..:/server/docs:ro
      - ../../site_output:/server/site_output
    working_dir: /server/
    # https://www.mkdocs.org/user-guide/cli/#mkdocs-serve
    command: ["serve","--config-file=${MKDOCS_CONFIG:-docs/mkdocs/mkdocs.yml}","--dev-addr=0.0.0.0:8000","--watch=docs/mkdocs"]
    ports:
      - "8000:8000"
    restart: unless-stopped