# Use a slim Python image as base
FROM python:3.14.7-slim

# Install system dependencies required for mkdocs and weasyprint
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libpango-1.0-0 \
        libpangoft2-1.0-0 \
        libharfbuzz-subset0 \
        libjpeg-dev \
        libopenjp2-7-dev \
        libffi-dev \
        unzip \
        udev \
        chromium && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install Python dependencies required for mkdocs and its plugins
RUN pip install --no-cache-dir\
    weasyprint \
    mkdocs \
    mkdocs-material \
    mkdocs-to-pdf \
    mkdocs-include-markdown-plugin \
    mkdocs-macros-plugin \
    mkdocs-mermaid2-plugin \
    mkdocs-kroki-plugin \
    mkdocs-print-site-plugin \
    qrcode \
    mkdocs-static-i18n[material] \
    mkdocs-slides \
    mkdocs-page-pdf \
    mkdocs-static-i18n[material]

# Install playwright for browser automation
RUN pip install --no-cache-dir playwright && playwright install chromium

# Copy the documentation source files into the container
COPY docs/src /server/docs/src
COPY docs/mkdocs /server/docs/mkdocs

WORKDIR /server

# Create the site output folder
RUN mkdir /server/site_output

# Set mkdocs as the container entrypoint
ENTRYPOINT ["mkdocs"]
CMD ["serve", "--config-file=docs/mkdocs/mkdocs.yml", "--dev-addr=0.0.0.0:8000"]